server:
  port: 8080
  servlet:
    context-path: /regServer
mybatis:
  mapper-locations: classpath:mybatis/*.xml

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharding_jdbc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/sharding_jdbc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver

  #定义数据源m1
  shardingsphere:
    datasource:
      names: ds
      #配置数据源具体内容，包含连接池，驱动，地址，用户名和密码
      #m1数据源配置
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/sharding_jdbc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root

    props:
      sql:
        show: true
    sharding:
      default-data-source-name: ds
      binding-tables: table_user_info
      tables:
        table_user_info:
          key-generator:
            column: id
            type: myKeyGen
          actual-data-nodes: ds.table_user_info_$->{["p1","p2"]}
          table-strategy:
            inline:
              sharding-column: position
              algorithm-expression: table_user_info_$->{position}

  flyway:
    enabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
    encoding: UTF-8
    # 开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder .
    out-of-order: false
    # 禁止清理数据库表
    clean-disabled: true
    # 校验
    validate-on-migrate: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    show-sql: true